version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.6
  commit-message:
    prefix: "[skip netlify]"
