name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.22.10
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    name: Ember Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.22.10
      - run: yarn install --frozen-lockfile
      - run: yarn test:ember